name: proverif

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - proverif
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          tags: |
            ghcr.io/akashisn/proverif:2.04
          target: proverif-2.04
          platforms: linux/amd64
          push: true